#!/usr/bin/env ruby
begin
  require 'tableparser'
rescue LoadError
  lib_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))
  $LOAD_PATH.unshift(lib_dir)
  require 'tableparser'
end

if STDIN.tty?
  abort "Usage: cat RESULTS | #{$PROGRAM_NAME} [--no-header]"
end

require 'csv'

skip_header = ARGV.include?('--no-header')

CSV.instance(STDOUT) do |csv|
  Tableparser.parse(STDIN) do |row|
    if skip_header
      skip_header = false
      next
    end
    csv << row
  end
end
